name: Release Drafter
 
on:
  pull_request:
    types: [opened, reopened, synchronize]
 
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    timeout-minutes: 15
 
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Get latest release tag
        id: get_tag
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const repo = context.repo;
            const { data } = await github.rest.repos.getLatestRelease({
                owner: repo.owner,
                repo: repo.repo,
            });
            let tag = data.tag_name;
            console.log(data)
            const regex = /sprint(\d+)/;
            const match = tag.match(regex);
            if (match) {
              const sprintNumber = parseInt(match[1]);
              tag = sprintNumber + 1;
            }
            return tag;
 
      - name: Check release date
        id: check_date
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const repo = context.repo;
            const { data } = await github.rest.repos.getLatestRelease({
              owner: repo.owner,
              repo: repo.repo,
            });
            const releaseDate = new Date(data.published_at);
            const currentDate = new Date();
            const diffTime = Math.abs(currentDate - releaseDate);
            const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
            return diffDays >= 1;
 
      # リリース日から1日以上経過している場合はリリースを作成する
      - name: create release
        if: ${{ steps.check_date.outputs.result == 'true' }}
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: true
          name: 'sprint${{ steps.get_tag.outputs.result }}'
          tag: 'sprint${{ steps.get_tag.outputs.result }}'
 
      # リリース日から2週間以上前の場合はリリースを作成しない
      - name: add label
        if: ${{ steps.check_date.outputs.result == 'false' }}
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          disable-releaser: true
